#!/usr/bin/env bash
# sentinel-setup-audio-mixing.sh <card_idx> <eq:on|off> [15 gain values in dB]
#
# Writes /etc/asound.conf so music (mpg123) and voice announcements
# (open_jtalk/espeak-ng via aplay) can be mixed and played at the same time
# through ALSA's dmix plugin, each through its own named PCM device so their
# volumes stay independent:
#
#   pcm.sentinel_dmix    dmix - the actual shared mixing stage
#   pcm.sentinel_music   music's entry point (mpg123 -a sentinel_music).
#                        Plain passthrough to dmix, or - when eq=on - a
#                        ladspa multiband EQ stage (mbeq, from swh-plugins)
#                        in front of dmix. mpg123 keeps its own volume
#                        control (V command / music_volume) - this PCM has
#                        no volume control of its own, it exists only to
#                        give music its own mixing slot.
#   pcm.sentinel_voice   voice's entry point (aplay -D sentinel_voice).
#                        A softvol stage in front of dmix, with its own
#                        "SentinelVoice" ALSA mixer control - so voice.py's
#                        volume changes never touch the shared hardware
#                        level (numid=1) that music/Bluetooth also share.
#
# Why root: /etc/asound.conf is root-writable only, and sentinel runs as a
# non-root user (CLAUDE.md #4) - same reasoning as
# sentinel-set-governor.sh/sentinel-set-hotspot-ssid.sh. sudoers cannot
# restrict argument *values*, so this script validates everything itself
# (that boundary is the actual security control, same pattern as those two
# scripts).
#
# Root cause this fixes: previously music played via mpg123's exclusive
# hold on the ALSA hw device, and voice.py fully stopped mpg123
# (music.duck_for_voice()) before speaking because bcm2835 without dmix
# only accepts one stream at a time. Separately, voice.py's volume control
# wrote to numid=1 - the same *hardware* register Bluetooth playback and
# the analog-output-routing Guardian check also use - so a voice
# announcement's volume could visibly change music's perceived loudness
# even after voice.py switches away from ducking. Routing both through
# dmix with their own independent controls fixes both: they can now play
# at once, and neither's volume control touches the other's.
set -uo pipefail

ok(){ printf '  [OK] %s\n' "$*"; }
w(){ printf '  [!!] %s\n' "$*" >&2; }
die(){ printf '[FAIL] %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo $0 $*"

CARD="${1:-}"
EQ="${2:-off}"
shift 2 2>/dev/null || true
BANDS=("$@")

[[ "$CARD" =~ ^[0-9]+$ && "$CARD" -le 31 ]] || die "card index must be an integer 0-31 (got: $CARD)"
[[ "$EQ" == "on" || "$EQ" == "off" ]] || die "eq must be 'on' or 'off' (got: $EQ)"

# mbeq (swh-plugins) is a 15-band graphic EQ at fixed ISO center
# frequencies. This order/count must match what modules/music.py sends.
BAND_HZ=(50 100 156 220 311 440 622 880 1250 1750 2500 3500 5000 10000 20000)
if [[ "$EQ" == "on" ]]; then
  [[ "${#BANDS[@]}" -eq 15 ]] || die "eq=on requires exactly 15 gain values (got ${#BANDS[@]})"
  for b in "${BANDS[@]}"; do
    [[ "$b" =~ ^-?[0-9]+(\.[0-9]+)?$ ]] || die "bad gain value: $b"
    # Clamp defensively even though the caller should already have - this
    # is the actual boundary sudoers can't enforce on its own.
    awk -v v="$b" 'BEGIN{ if (v < -20 || v > 20) exit 1 }' || die "gain out of range (-20..20 dB): $b"
  done
fi

ASOUND=/etc/asound.conf
TMP=$(mktemp)

find_ladspa_plugin() {
  # Path varies by distro/arch (multiarch dirs differ between armhf/arm64) -
  # search rather than hardcode, same reasoning as voice.py's Open JTalk
  # dictionary/voice-model discovery (CLAUDE.md #27).
  for p in /usr/lib/ladspa /usr/lib/*/ladspa /usr/lib64/ladspa; do
    [[ -d "$p" ]] || continue
    local f
    f=$(find "$p" -maxdepth 1 -iname 'mbeq*.so' 2>/dev/null | head -1)
    [[ -n "$f" ]] && { echo "$p"; return 0; }
  done
  return 1
}

write_conf() {
  local with_eq="$1"
  local ladspa_dir="" controls=""
  if [[ "$with_eq" == "on" ]]; then
    ladspa_dir=$(find_ladspa_plugin) || return 1
    local parts=()
    for b in "${BANDS[@]}"; do parts+=("$b"); done
    controls=$(IFS=' '; echo "${parts[*]}")
  fi

  cat > "$TMP" <<EOF
# Generated by sentinel-setup-audio-mixing.sh - do not edit by hand, it is
# rewritten on every settings change. See that script for the reasoning.

pcm.sentinel_dmix {
    type dmix
    ipc_key 5678293
    ipc_perm 0666
    slave {
        pcm "hw:$CARD,0"
        rate 44100
        format S16_LE
        channels 2
        period_time 0
        period_size 1024
        buffer_size 8192
    }
}

EOF

  if [[ "$with_eq" == "on" ]]; then
    cat >> "$TMP" <<EOF
pcm.sentinel_music {
    type ladspa
    slave.pcm "sentinel_dmix"
    path "$ladspa_dir"
    plugins [
        {
            label "mbeq"
            input {
                controls [ $controls ]
            }
        }
    ]
}

EOF
  else
    cat >> "$TMP" <<EOF
pcm.sentinel_music {
    type plug
    slave.pcm "sentinel_dmix"
}

EOF
  fi

  cat >> "$TMP" <<EOF
pcm.sentinel_voice {
    type softvol
    slave.pcm "sentinel_dmix"
    control {
        name "SentinelVoice"
        card $CARD
    }
    min_dB -51.0
    max_dB 0.0
}

pcm.!default {
    type plug
    slave.pcm "sentinel_dmix"
}

ctl.!default {
    type hw
    card $CARD
}
EOF
  return 0
}

test_pcm() {
  local dev="$1"
  local out
  out=$(mktemp)
  aplay -D "$dev" -f S16_LE -r 44100 -c 2 -q /dev/zero >"$out" 2>&1 &
  local pid=$!
  sleep 0.7
  local result=1
  if kill -0 "$pid" 2>/dev/null; then
    result=0
    kill "$pid" 2>/dev/null
  fi
  wait "$pid" 2>/dev/null
  if [[ "$result" -ne 0 ]]; then
    w "aplay -D $dev failed:"
    sed 's/^/       /' "$out" >&2
  fi
  rm -f "$out"
  return "$result"
}

# Never leave the machine worse off than before: keep a backup of whatever
# was at $ASOUND (including "nothing", i.e. no file) and restore it if
# every attempt below still fails its playback test. Without this, a card
# index that's wrong or a machine with no LADSPA plugin installed could
# turn "audio worked, just without mixing" into "audio doesn't work at
# all" - exactly the kind of regression CLAUDE.md #8's can_write()
# discipline exists to prevent.
BACKUP=$(mktemp)
HAD_EXISTING=0
if [[ -f "$ASOUND" ]]; then
  cp "$ASOUND" "$BACKUP"
  HAD_EXISTING=1
fi
restore_backup() {
  if [[ "$HAD_EXISTING" -eq 1 ]]; then
    cp "$BACKUP" "$ASOUND"
  else
    rm -f "$ASOUND"
  fi
  rm -f "$BACKUP"
}

if ! write_conf "$EQ"; then
  w "EQ requested but no mbeq LADSPA plugin found (install swh-plugins) - falling back to no EQ"
  EQ=off
  write_conf off
fi

cp "$TMP" "$ASOUND"
rm -f "$TMP"

# Functional test, not just "the file parsed" - same philosophy as
# sentinel-fix-storage-owner.sh's can_write() (CLAUDE.md #8): a config that
# merely looks syntactically fine can still fail to actually open the
# device (missing plugin, bad card index, ...).
FAILED=0
test_pcm sentinel_music || FAILED=1
test_pcm sentinel_voice || FAILED=1

if [[ "$FAILED" -eq 1 && "$EQ" == "on" ]]; then
  w "EQ config failed its playback test - retrying without EQ"
  write_conf off
  cp "$TMP" "$ASOUND"
  rm -f "$TMP"
  FAILED=0
  test_pcm sentinel_music || FAILED=1
  test_pcm sentinel_voice || FAILED=1
  EQ=off
fi

if [[ "$FAILED" -eq 1 ]]; then
  restore_backup
  die "sentinel_music/sentinel_voice still fail their playback test even without EQ - restored the previous $ASOUND unchanged. Check 'aplay -l' and the card index passed ($CARD)."
fi

rm -f "$BACKUP"
ok "Wrote $ASOUND (card=$CARD, eq=$EQ) and verified both devices play"
echo "EQ_ACTIVE=$EQ"
